name: turms_chat_demo
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cross_file: ^0.3.3+8
  data_table_2: ^2.5.9
  diff_match_patch: ^0.4.1
  dotted_border: ^2.1.0
  drift: ^2.14.0
  equatable: ^2.0.5 # required by flutter_quill
  extended_image: ^8.2.0
  file_picker: ^6.1.1
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
#  flutter_quill: ^8.5.3
  flutter_keyboard_visibility: ^5.4.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  gal: ^2.2.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: any
  logger: ^2.0.2+1
  markdown: ^7.1.1
  # TODO: Wait for Flutter official solution (https://github.com/flutter/flutter/issues/102560)
  # We need this dependency to support icon weight.
  material_symbols_icons: ^4.2713.0
  path: ^1.8.3
  path_provider: ^2.1.1
  photo_view: ^0.14.0 # required by flutter_quill. TODO: Use "extended_image"
  quiver: ^3.2.1 # required by flutter_quill
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.18
  super_clipboard: ^0.7.3
  # Note that the Flutter team recommends "super_drag_and_drop" officially.
  super_drag_and_drop: ^0.7.3
  turms_client_dart:
    path: ../turms-client-dart/
  universal_html: ^2.2.4
  url_launcher: ^6.2.2
  video_player: ^2.8.1
  # TODO: Wait for Flutter official solution (https://github.com/flutter/flutter/issues/31373)
  window_manager: ^0.3.7
#  flutter_quill_extensions: ^0.6.9
#  super_editor_markdown: ^0.1.5

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  drift_dev: ^2.14.0
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
#  matcher: ^0.12.16
#  mockito: ^5.4.2
  riverpod_lint: ^3.0.0-dev.4

dependency_overrides:
  # We need to override to introduce "super_editor_markdown"
#  http: ^1.1.0
#  markdown: ^7.1.1
#  uuid: ^4.1.0
#  analyzer: ^6.0.0

flutter:
  # Ensures that the Material Icons font is included with our application
  uses-material-design: true
  # Used to generate l10n files
  generate: true
  assets:
    - assets/fonts/
    - assets/images/

flutter_gen:
  output: lib/infra/assets/