name: turms_chat_demo
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animations: ^2.0.11
  async: ^2.11.0
  background_downloader: ^8.0.5
  convert: ^3.1.1
  cross_file: ^0.3.3+8
  crypto: ^3.0.3
  # dart_mappable
  data_table_2: ^2.5.10
  device_info_plus: ^9.1.1
  diff_match_patch: ^0.4.1
  dotted_border: ^2.1.0
  drift: ^2.14.1
  equatable: ^2.0.5 # required by flutter_quill
  extended_image: ^8.2.0
  file_picker: ^6.1.1
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_local_notifications: ^16.3.0
  flutter_localizations:
    sdk: flutter
  flutter_quill:
    path: ../../fork/flutter-quill
#    git:
#      url: https://github.com/JamesChenX/flutter-quill
  #      path: master
  flutter_riverpod: ^3.0.0-dev.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  gal: ^2.2.0
  google_fonts: ^6.1.0
  html2md: ^1.3.1
  http: ^1.1.2
  image_picker: ^1.0.6
  intl: any
  launch_at_startup: ^0.2.2
  logger: ^2.0.2+1
  # TODO: Wait for Flutter official solution (https://github.com/flutter/flutter/issues/102560)
  # We need this dependency to support icon weight.
  material_symbols_icons: ^4.2713.0
  media_kit_libs_android_video: any
  media_kit_libs_ios_video: any
  media_kit_libs_linux: any
  media_kit_libs_macos_video: any
  media_kit_libs_windows_video: any
  open_filex: ^4.3.4
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.1
#  permission_handler: ^11.1.0
  photo_view: ^0.14.0 # required by flutter_quill. TODO: Use "extended_image"
  pub_semver: ^2.1.4
  quiver: ^3.2.1 # required by flutter_quill
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.18
  super_clipboard: ^0.8.2+1
  # Note: The Flutter team recommends "super_drag_and_drop".
  # https://github.com/flutter/flutter/issues/30719#issuecomment-1776119627
  super_drag_and_drop: ^0.8.2+1
  super_hot_key: ^0.8.2+1
  # TODO: Wait for Flutter official solution (https://github.com/flutter/flutter/issues/81644)
  tray_manager: ^0.2.1
  turms_client_dart:
    path: ../turms-client-dart/
  universal_html: ^2.2.4
  url_launcher: ^6.2.2
  video_player: ^2.8.2
  video_player_media_kit: ^1.0.5
  # TODO: Wait for Flutter official solution (https://github.com/flutter/flutter/issues/31373)
  window_manager: ^0.3.7
  windows_notification: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  drift_dev: ^2.14.1
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
#  matcher: ^0.12.16
#  mockito: ^5.4.2
  riverpod_lint: ^3.0.0-dev.4

flutter:
  # Ensures that the Material Icons font is included with our application
  uses-material-design: true
  # Used to generate l10n files
  generate: true
  assets:
    - assets/fonts/
    - assets/images/

flutter_gen:
  output: lib/infra/assets/