name: turms_chat_demo
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  # flutter.dev
  animations: ^2.0.11
  # dart.dev
  async: ^2.11.0
  # bbflight.com
  # No web support
  background_downloader: ^8.2.1
  # dart.dev
  convert: ^3.1.1
  # flutter.dev
  cross_file: ^0.3.3+8
  # dart.dev
  crypto: ^3.0.3
  # dart_mappable
  # saplin.blogspot.com
  data_table_2: ^2.5.11
  # fluttercommunity.dev
  device_info_plus: ^9.1.2
  # unverified uploader
  dotted_border: ^2.1.0
  # simonbinder.eu
  drift: ^2.15.0
  # miguelruivo.com
  file_picker: ^6.1.1
  # dart.dev
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  # fluttercandies
  flutter_image_compress: ^2.1.0
  # jasonrai.ca
  flutter_keyboard_visibility: ^6.0.0
  # dexterx.dev
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  # dash-overflow.net
  flutter_markdown: ^0.6.20+1
  flutter_riverpod: ^3.0.0-dev.3
  flutter_secure_storage: ^9.0.0
  # dnfield.dev
  flutter_svg: ^2.0.10+1
  gal: ^2.3.0
  # material.io
  google_fonts: ^6.1.0
  html2md: ^1.3.1
  http: ^1.2.0
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: any
  json_rpc_2: ^3.0.2
  logger: ^2.0.2+1
  # hiveright.tech
  # TODO: Wait for Flutter official solution (https://github.com/flutter/flutter/issues/102560)
  # We need this dependency to support icon weight.
  material_symbols_icons: ^4.2719.1
  media_kit_libs_android_video: any
  media_kit_libs_ios_video: any
  media_kit_libs_linux: any
  media_kit_libs_macos_video: any
  media_kit_libs_windows_video: any
  open_filex: ^4.4.0
  package_info_plus: ^5.0.1
  path: ^1.8.3
  path_provider: ^2.1.2
  #  permission_handler: ^11.1.0
  pub_semver: ^2.1.4
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: ^2.2.2
  shelf_web_socket: ^1.0.4
  sqlite3_flutter_libs: ^0.5.19+1
  super_clipboard: ^0.8.5
  # Note: The Flutter team recommends "super_drag_and_drop".
  # https://github.com/flutter/flutter/issues/30719#issuecomment-1776119627
  super_drag_and_drop: ^0.8.5
  super_hot_key: ^0.8.5
  # TODO: Wait for Flutter official solution: https://github.com/flutter/flutter/issues/81644
  tray_manager: ^0.2.1
  turms_client_dart:
    path: ../turms-client-dart/
  universal_html: ^2.2.4
  url_launcher: ^6.2.5
  video_player: ^2.8.2
  video_player_media_kit: ^1.0.5
  visibility_detector: ^0.4.0+2
  # TODO: Wait for Flutter official solution (https://github.com/flutter/flutter/issues/31373)
  web_socket_channel: ^2.4.3
  window_manager: ^0.3.8
  windows_notification: ^1.0.0
  youtube_explode_dart: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.8
  # invertase.io
  custom_lint: ^0.5.11
  drift_dev: ^2.15.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  #  matcher: ^0.12.16
  #  mockito: ^5.4.2
  riverpod_lint: ^3.0.0-dev.4

flutter:
  # Ensures that the Material Icons font is included with our application
  uses-material-design: true
  # Used to generate l10n files
  generate: true
  assets:
#    - assets/fonts/
    - assets/images/

flutter_gen:
  output: lib/infra/assets/