name: turms_chat_demo
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # flutter.dev
  animations: ^2.0.11
  # dart.dev
  async: ^2.11.0
  # bbflight.com
  # Note: No web support
  background_downloader: ^8.4.1
  # dart.dev
  convert: ^3.1.1
  # flutter.dev
  cross_file: ^0.3.4+1
  # dart.dev
  crypto: ^3.0.3
  # fluttercommunity.dev
  device_info_plus: ^10.0.1
  # unverified uploader
  dotted_border: ^2.1.0
  # simonbinder.eu
  drift: ^2.16.0
  # miguelruivo.com
  file_picker: ^8.0.0+1
  # dart.dev
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  # fluttercandies
  flutter_image_compress: ^2.2.0
  # jasonrai.ca
  flutter_keyboard_visibility: ^6.0.0
  # dexterx.dev
  flutter_local_notifications: ^17.0.0
  # Flutter
  flutter_localizations:
    sdk: flutter
  # dash-overflow.net
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  # dnfield.dev
  flutter_svg: ^2.0.10+1
  # midoridesign.studio
  gal: ^2.3.0
  # material.io
  google_fonts: ^6.2.1
  # dart.dev
  http: ^1.2.1
  # loki3d.com
  image: ^4.1.7
  # flutter.dev
  image_picker: ^1.0.7
  intl: any
  # tools.dart.dev
  json_rpc_2: ^3.0.2
  # hiveright.tech
  # TODO: Wait for Flutter official solution: https://github.com/flutter/flutter/issues/102560
  # We need this dependency to support icon weight.
  material_symbols_icons: ^4.2719.3
  # media-kit.dev
  media_kit: ^1.1.10+1
  media_kit_libs_audio: ^1.0.4
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
#  media_kit_libs_android_video: any
#  media_kit_libs_ios_video: any
#  media_kit_libs_linux: any
#  media_kit_libs_macos_video: any
#  media_kit_libs_windows_video: any
  # buildtoapp.com
  open_filex: ^4.4.0
  # fluttercommunity.dev
  package_info_plus: ^7.0.0
  # dart.dev
  path: ^1.9.0
  # flutter.dev
  path_provider: ^2.1.2
  # tools.dart.dev
  pub_semver: ^2.1.4
  # dash-overflow.net
  riverpod_annotation: ^2.3.5
  # tools.dart.dev
  shelf_web_socket: ^1.0.4
  # simonbinder.eu
  sqlite3_flutter_libs: ^0.5.20
  squadron: ^5.1.6
  # nativeshell.dev
  super_clipboard: ^0.8.10
  # nativeshell.dev
  # Note: The Flutter team recommends "super_drag_and_drop".
  super_drag_and_drop: ^0.8.10
  # nativeshell.dev
  super_hot_key: ^0.8.10
  # leanflutter.dev
  # TODO: Wait for Flutter official solution: https://github.com/flutter/flutter/issues/81644
  tray_manager: ^0.2.2
  turms_client_dart:
    path: ../turms-client-dart/
  universal_html: ^2.2.4
  url_launcher: ^6.2.5
  # flutter.dev
  video_player: ^2.8.4
  # media-kit.dev
  video_player_media_kit: ^1.0.5
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^2.4.4
  # TODO: Wait for Flutter official solution (https://github.com/flutter/flutter/issues/31373)
  window_manager: ^0.3.8
  windows_notification: ^1.0.0
  youtube_explode_dart: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.9
  # invertase.io
  custom_lint: ^0.6.4
  drift_dev: ^2.16.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  #  matcher: ^0.12.16
  #  mockito: ^5.4.2
  # Flutter
  # TODO: Wait for Linux support: https://github.com/flutter/flutter/issues/73740
  pigeon: ^18.0.0
  riverpod_lint: ^2.3.10

flutter:
  # Ensures that the Material Icons font is included with our application
  uses-material-design: true
  # Used to generate l10n files
  generate: true
  assets:
#    - assets/fonts/
    - assets/images/

flutter_gen:
  output: lib/infra/assets/